// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, server;

  express = require('express');

  app = express();

  app.get("/", function(req, res) {
    return res.send("Hello World");
  });

  server = app.listen(4000, function() {
    return console.log('Listening on port %d', server.address().port);
  });

}).call(this);
